export {
  generatedDiagnosticCategories,
  isGeneratedDiagnosticCategory,
  type GeneratedDiagnosticCategory,
} from "./generated/diagnostic-categories.js";
export {
  assertPositiveRational,
  compareRationals,
  deserializeRational,
  multiplyRationals,
  normalizeRational,
  parseBigIntString,
  rationalJsonSchema,
  serializeBigInt,
  type BigIntString,
  type NormalizedRational,
} from "./rational.js";
export {
  assertProjectDocument,
  getProjectDocumentJsonSchema,
  projectDocumentKinds,
  projectDocumentSchemaBundle,
  validateProjectDocument,
  type ApprovalStateDocument,
  type AcceptedExceptionDocument,
  type AlternateTakeDocument,
  type AnnotationDocument,
  type AnnotationGeometry,
  type AudioAutomationKeyframe,
  type AudioAutomationLane,
  type AudioBusKind,
  type AudioChannelLayout,
  type AudioCrossfade,
  type AudioDuckingRule,
  type AudioGraphBus,
  type AudioGraphClip,
  type AudioGraphDocument,
  type AudioGraphSource,
  type AudioProcessingReference,
  type AudioSyncAnchor,
  type AudioChannelMap,
  type CaptionCueDocument,
  type CaptionDocument,
  type CaptionStyleTemplate,
  type AssetsDocument,
  type AssetRecord,
  type AutosaveMetadataDocument,
  type ChaiProjectDocument,
  type CurrentRevisionPointer,
  type DocumentValidationResult,
  type NamedVersionsDocument,
  type ProjectDocumentByKind,
  type ProjectDocumentKind,
  type QaState,
  type ReviewActionDocument,
  type ReviewActor,
  type ReviewBundleDocument,
  type ReviewComparisonDocument,
  type ReviewIssueDocument,
  type ReviewIssueTransition,
  type ReviewRequestDocument,
  type ReviewStateDocument,
  type SchemaVersion,
  type SettingsDocument,
  type StructuralValidationIssue,
  type TimelineClip,
  type TimelineDocument,
  type TimelineMarker,
  type TimelineTrack,
  type TranscriptCorrectionState,
  type TranscriptDocument,
  type TranscriptPhrase,
  type TranscriptSourceAudio,
  type TranscriptSpeaker,
  type TranscriptWord,
  type TransactionDocument,
} from "./project-documents.js";
export {
  validateProjectSnapshot,
  type ProjectRevisionSnapshot,
  type ProjectValidationReport,
  type SemanticValidationIssue,
} from "./project-validation.js";
export {
  canonicalizeJson,
  sha256CanonicalJson,
  stringifyCanonicalJson,
  type JsonPrimitive,
  type JsonValue,
} from "./canonical-json.js";
export {
  canonicalProjectDirectories,
  hashRevisionDocuments,
  initializeProjectFolder,
  revisionDocumentNames,
  type InitializedProject,
  type InitializeProjectOptions,
} from "./project-folder.js";
export {
  auditRevisionStorage,
  buildOptimisticConflictReport,
  commitProjectRevision,
  loadCurrentProjectRevision,
  loadProjectRevision,
  type CommitActor,
  type CommitProjectRevisionOptions,
  type LoadedProjectRevision,
  type LoadedImmutableRevision,
  type OptimisticConflictReport,
  type RevisionCommitCheckpoint,
  type RevisionCommitResult,
  type RevisionContentDocuments,
  type RevisionStorageAudit,
} from "./revision-store.js";
export {
  acquireProjectMutationLock,
  projectMutationLockName,
  readProjectMutationLock,
  type AcquireProjectMutationLockOptions,
  type ProjectMutationLock,
  type ProjectMutationLockDocument,
} from "./project-lock.js";
export {
  assertCommandEnvelope,
  commandEnvelopeJsonSchema,
  validateCommandEnvelope,
  type AudioEditCommand,
  type AnnotationEditCommand,
  type AssetRegisterCommand,
  type AssetRelinkCommand,
  type AssetReplaceCommand,
  type AssetManifestUpsertCommand,
  type CaptureCreateCommand,
  type CommandEnvelopeValidationResult,
  type CommandKind,
  type CommandScope,
  type HistoryMoveCommand,
  type LifecycleTransitionCommand,
  type LanguageEditCommand,
  type ProjectCommandEnvelope,
  type ProjectRenameCommand,
  type ReadInspectCommand,
  type SourceEditCommand,
  type TimelineReplaceCommand,
  type TimelineEditCommand,
  type VersionCreateCommand,
} from "./command-envelope.js";
export {
  executeProjectCommand,
  rebuildNamedVersions,
  reconcileWorkingSources,
  type CommandExecutionReceipt,
  type CommandExecutionStatus,
  type ExecuteProjectCommandOptions,
} from "./command-engine.js";
export {
  createProjectAutosave,
  createDebouncedAutosaveController,
  markProjectCleanShutdown,
  markProjectOpened,
  readAutosaveMetadata,
  restoreProjectAutosave,
  scanAutosaveRecovery,
  type AutosaveCandidate,
  type AutosaveReason,
  type CreateAutosaveOptions,
  type DebouncedAutosaveController,
  type DebouncedAutosaveOptions,
  type RecoveryScan,
  type RestoreAutosaveOptions,
} from "./autosave-store.js";
export {
  currentProjectSchemaVersion,
  migrateProjectArtifactFile,
  migrateProjectDocumentBundle,
  projectMigrationRegistry,
  rollbackProjectArtifactMigration,
  type MigrateArtifactFileOptions,
  type MigrationRegistryEntry,
  type ProjectBundleMigrationResult,
  type ProjectMigrationReport,
} from "./migration.js";
export {
  abortSourceEdit,
  beginSourceEdit,
  commitSourceEdit,
  readSourceEditSession,
  type BeginSourceEditOptions,
  type CommitSourceEditOptions,
  type SourceEditSession,
} from "./source-edit-session.js";
export {
  assertNoAsyncOperationBarriers,
  beginAsyncOperation,
  completeAsyncOperation,
  listAsyncOperationBarriers,
  type AsyncOperationBarrier,
  type BeginAsyncOperationOptions,
} from "./operation-barrier.js";

export const schemaPackageBoundary = "authoritative schemas, migrations, and generated validators" as const;
