import type { BridgeCapability } from "./authorization.js";

export interface BridgeCommandDescriptor {
  readonly name: string;
  readonly path: readonly string[];
  readonly capability: BridgeCapability;
  readonly mutatesProject: boolean;
  readonly requiresFreshContext: boolean;
  readonly synopsis: string;
}

export const bridgeCommandCatalog: readonly BridgeCommandDescriptor[] = [
  {
    name: "status",
    path: ["status"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "status",
  },
  {
    name: "project.create",
    path: ["project", "create"],
    capability: "project.write",
    mutatesProject: true,
    requiresFreshContext: false,
    synopsis: "project create <path> <title> [--starter empty|showcase|launch-film]",
  },
  {
    name: "project.open",
    path: ["project", "open"],
    capability: "project.write",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "project open <path>",
  },
  {
    name: "project.close",
    path: ["project", "close"],
    capability: "project.write",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "project close",
  },
  {
    name: "project.snapshot",
    path: ["project", "snapshot"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "project snapshot",
  },
  {
    name: "project.revisions",
    path: ["project", "revisions"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "project revisions",
  },
  {
    name: "project.recent",
    path: ["project", "recent"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "project recent",
  },
  {
    name: "project.named-versions",
    path: ["project", "named-versions"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "project named-versions",
  },
  {
    name: "project.migration",
    path: ["project", "migration"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "project migration",
  },
  {
    name: "project.repair",
    path: ["project", "repair"],
    capability: "project.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "project repair",
  },
  {
    name: "selection.get",
    path: ["selection", "get"],
    capability: "selection.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "selection get",
  },
  {
    name: "selection.set",
    path: ["selection", "set"],
    capability: "selection.write",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "selection set <id...>",
  },
  {
    name: "context.latest",
    path: ["context", "latest"],
    capability: "context.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "context latest",
  },
  {
    name: "asset.upload",
    path: ["asset", "upload"],
    capability: "asset.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "asset upload <file> --kind <kind> --rights <rights> [--id <asset-id>]",
  },
  {
    name: "asset.import",
    path: ["asset", "import"],
    capability: "asset.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "asset import <source-path> --kind <kind> --rights <rights> [--id <asset-id>]",
  },
  {
    name: "asset.search",
    path: ["asset", "search"],
    capability: "asset.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "asset search [text] [--kind <kind>] [--rights <rights>] [--limit <count>]",
  },
  {
    name: "asset.inspect",
    path: ["asset", "inspect"],
    capability: "asset.process",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "asset inspect <asset-id> [--wait]",
  },
  {
    name: "asset.proxy",
    path: ["asset", "proxy"],
    capability: "asset.process",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "asset proxy <asset-id> [--wait]",
  },
  {
    name: "asset.usage",
    path: ["asset", "usage"],
    capability: "asset.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "asset usage <asset-id>",
  },
  {
    name: "asset.relink",
    path: ["asset", "relink"],
    capability: "asset.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "asset relink <asset-id> <source-path>",
  },
  {
    name: "asset.replace",
    path: ["asset", "replace"],
    capability: "asset.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "asset replace <asset-id> <source-path> --hash <sha256> --kind <kind> --rights <rights>",
  },
  {
    name: "asset.rights",
    path: ["asset", "rights"],
    capability: "asset.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "asset rights <records-json-file|->",
  },
  {
    name: "asset.frame",
    path: ["asset", "frame"],
    capability: "asset.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "asset frame <asset-id> <frame> <destination.png>",
  },
  {
    name: "capture.current",
    path: ["capture", "current"],
    capability: "capture.create",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "capture current [--frame <frame>] [--label <label>]",
  },
  {
    name: "capture.range",
    path: ["capture", "range"],
    capability: "capture.create",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "capture range <start> <end> [--profile <profile-id>]",
  },
  {
    name: "capture.list",
    path: ["capture", "list"],
    capability: "context.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "capture list",
  },
  {
    name: "preview.start",
    path: ["preview", "start"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "preview start",
  },
  {
    name: "preview.state",
    path: ["preview", "state"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "preview state",
  },
  {
    name: "preview.play",
    path: ["preview", "play"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview play",
  },
  {
    name: "preview.pause",
    path: ["preview", "pause"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview pause",
  },
  {
    name: "preview.seek",
    path: ["preview", "seek"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview seek <frame>",
  },
  {
    name: "preview.step",
    path: ["preview", "step"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview step <delta>",
  },
  {
    name: "preview.stop",
    path: ["preview", "stop"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview stop",
  },
  {
    name: "preview.unload",
    path: ["preview", "unload"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "preview unload",
  },
  {
    name: "preview.quality",
    path: ["preview", "quality"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview quality <draft|balanced|full> [--truth <mode>]",
  },
  {
    name: "preview.rate",
    path: ["preview", "rate"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview rate <numerator/denominator>",
  },
  {
    name: "preview.in-out",
    path: ["preview", "in-out"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview in-out <start:endExclusive|clear>",
  },
  {
    name: "preview.preload",
    path: ["preview", "preload"],
    capability: "preview.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "preview preload [--before <frames>] [--after <frames>]",
  },
  {
    name: "render.profiles",
    path: ["render", "profiles"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render profiles",
  },
  {
    name: "render.plan",
    path: ["render", "plan"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "render plan --profile <id> [--frame <frame>|--range <start:end>]",
  },
  {
    name: "render.start",
    path: ["render", "start"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "render start --profile <id> [--frame <frame>|--range <start:end>] [--wait]",
  },
  {
    name: "render.status",
    path: ["render", "status"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render status <job>",
  },
  {
    name: "render.cancel",
    path: ["render", "cancel"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render cancel <job>",
  },
  {
    name: "render.retry",
    path: ["render", "retry"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render retry <job> [--wait]",
  },
  {
    name: "render.outputs",
    path: ["render", "outputs"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render outputs",
  },
  {
    name: "render.output",
    path: ["render", "output"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render output <output-id>",
  },
  {
    name: "render.requests",
    path: ["render", "requests"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render requests",
  },
  {
    name: "render.queue",
    path: ["render", "queue"],
    capability: "status.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render queue",
  },
  {
    name: "render.duplicate",
    path: ["render", "duplicate"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render duplicate <job-id> [--wait]",
  },
  {
    name: "render.reprioritize",
    path: ["render", "reprioritize"],
    capability: "render.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "render reprioritize <job-id> --priority <-100..100>",
  },
  {
    name: "qa.run",
    path: ["qa", "run"],
    capability: "qa.run",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "qa run [output-id] [--wait]",
  },
  {
    name: "qa.latest",
    path: ["qa", "latest"],
    capability: "qa.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "qa latest",
  },
  {
    name: "qa.get",
    path: ["qa", "get"],
    capability: "qa.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "qa get <output-id>",
  },
  {
    name: "receipt.get",
    path: ["receipt", "get"],
    capability: "receipt.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "receipt get <output-id>",
  },
  {
    name: "artifact.get",
    path: ["artifact", "get"],
    capability: "receipt.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "artifact get <output-id> <index> <destination>",
  },
  {
    name: "annotation.list",
    path: ["annotation", "list"],
    capability: "annotation.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "annotation list",
  },
  {
    name: "annotation.create",
    path: ["annotation", "create"],
    capability: "annotation.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "annotation create <json-file|->",
  },
  {
    name: "annotation.update",
    path: ["annotation", "update"],
    capability: "annotation.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "annotation update <annotation-id> <json-file|->",
  },
  {
    name: "annotation.delete",
    path: ["annotation", "delete"],
    capability: "annotation.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "annotation delete <annotation-id>",
  },
  {
    name: "comparison.list",
    path: ["comparison", "list"],
    capability: "annotation.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "comparison list",
  },
  {
    name: "comparison.create",
    path: ["comparison", "create"],
    capability: "annotation.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "comparison create <left-capture> <right-capture> [--mode wipe] [--split 0.5]",
  },
  {
    name: "comparison.delete",
    path: ["comparison", "delete"],
    capability: "annotation.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "comparison delete <comparison-id>",
  },
  {
    name: "review.workspace",
    path: ["review", "workspace"],
    capability: "review.read",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "review workspace",
  },
  {
    name: "review.apply",
    path: ["review", "apply"],
    capability: "review.write",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "review apply <safe-operation-json-file|->",
  },
  {
    name: "command.apply",
    path: ["command", "apply"],
    capability: "command.execute",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "command apply <json-file|->",
  },
  {
    name: "command.validate",
    path: ["command", "validate"],
    capability: "command.execute",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "command validate <json-file|->",
  },
  {
    name: "jobs.list",
    path: ["jobs", "list"],
    capability: "job.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "jobs list",
  },
  {
    name: "jobs.status",
    path: ["jobs", "status"],
    capability: "job.read",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "jobs status <job-id>",
  },
  {
    name: "jobs.cancel",
    path: ["jobs", "cancel"],
    capability: "job.control",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "jobs cancel <job-id>",
  },
  {
    name: "source.edit.begin",
    path: ["source", "edit", "begin"],
    capability: "source.edit",
    mutatesProject: false,
    requiresFreshContext: true,
    synopsis: "source edit begin <path>",
  },
  {
    name: "source.edit.commit",
    path: ["source", "edit", "commit"],
    capability: "source.edit",
    mutatesProject: true,
    requiresFreshContext: true,
    synopsis: "source edit commit <session> <file>",
  },
  {
    name: "source.edit.abort",
    path: ["source", "edit", "abort"],
    capability: "source.edit",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "source edit abort <session>",
  },
  {
    name: "source.edit.status",
    path: ["source", "edit", "status"],
    capability: "source.edit",
    mutatesProject: false,
    requiresFreshContext: false,
    synopsis: "source edit status <session>",
  },
] as const satisfies readonly BridgeCommandDescriptor[];

export type BridgeCommandName = (typeof bridgeCommandCatalog)[number]["name"];

export const bridgeDiscoveryDocument = {
  schemaVersion: "1.0.0" as const,
  surface: "local-codex-bridge" as const,
  networkPush: false as const,
  commands: bridgeCommandCatalog,
};
