import type { GeneratedDiagnosticCategory } from "@chai-studio/schema";

export {
  createEmptyTimelineSnapshot,
  stableEntityId,
  type AutomationLaneSnapshot,
  type AudioBusSnapshot,
  type BridgeSnapshot,
  type CaptionSnapshot,
  type ClipSnapshot,
  type InterpolationKind,
  type KeyframeSnapshot,
  type MarkerSnapshot,
  type NestedSequenceSnapshot,
  type SelectionSnapshot,
  type StableEntityId,
  type TimelineEngine,
  type TimelinePropertyCapability,
  type TimelinePropertyState,
  type TimelinePropertyValue,
  type TimelineSnapshotV1,
  type TimelineTrackKind,
  type TrackSnapshot,
  type TransitionSnapshot,
} from "./model.js";
export {
  addFrames,
  clampFrameToRange,
  createFrameRange,
  frameRangeContains,
  frameRangeDuration,
  frameRangeFromDuration,
  frameRangesOverlap,
  intersectFrameRanges,
  masterFrame,
  maximumMasterFrame,
  minimumMasterFrame,
  subtractFrames,
  translateFrameRange,
  type FrameRange,
  type MasterFrame,
} from "./range.js";
export {
  composeFrameTransforms,
  createTimelineSourceTransform,
  formatTimecode,
  invertFrameTransform,
  mapFrameExact,
  mapRangeExact,
  type ExactFrameTransform,
  type FrameRoundingPolicy,
  type TimecodeDisplay,
  type TimelineSourceTransformInput,
} from "./transform.js";
export {
  assertValidTimelineCore,
  audibleTracks,
  orderedAudioBuses,
  orderedTracks,
  validateClipPlacement,
  validateTimelineCore,
  visualStack,
  type ClipPlacementReport,
  type TimelineValidationIssue,
  type TimelineValidationReport,
} from "./validation.js";
export {
  collectSnapCandidates,
  resolveSnap,
  snapKindPriority,
  type CollectSnapOptions,
  type ResolveSnapOptions,
  type SnapCandidate,
  type SnapCandidateKind,
  type SnapResolution,
  type TranscriptPhraseSnapSource,
} from "./snap.js";
export {
  copyTimelineClips,
  createBladeCommand,
  createNudgeCommand,
  executeTimelineCommand,
  type AddMarkerCommand,
  type AddAutomationLaneCommand,
  type AddKeyframeCommand,
  type AddKeyframesCommand,
  type AddTrackCommand,
  type ClearInOutRangeCommand,
  type ClipMoveTarget,
  type ClipSplitMapping,
  type ClipTrimTarget,
  type DuplicateClipMapping,
  type DuplicateClipsCommand,
  type InsertClipCommand,
  type MoveClipsCommand,
  type MoveClipsToNewTrackCommand,
  type OverwriteClipCommand,
  type PasteClipMapping,
  type PasteClipsCommand,
  type ReplaceClipCommand,
  type ReorderTracksCommand,
  type RemoveTrackCommand,
  type RestoreTimelineCommand,
  type RemoveClipsCommand,
  type RemoveMarkersCommand,
  type RemoveAutomationLanesCommand,
  type RemoveKeyframesCommand,
  type SelectTimelineCommand,
  type SetClipGroupCommand,
  type SetClipLinkCommand,
  type SetInOutRangeCommand,
  type SplitClipsCommand,
  type TimelineClipboard,
  type TimelineEditCommand,
  type TimelineEditResult,
  type TimelineSelectionMode,
  type TrimClipsCommand,
  type UpdateMarkerCommand,
  type UpdateKeyframeCommand,
  type UpdateKeyframesCommand,
  type UpdateClipPropertiesCommand,
  type ConvertClipPropertiesToSharedCommand,
  type UpdateClipMetadataCommand,
  type UpdateTrackMetadataCommand,
} from "./commands.js";
export {
  curveTangentsForPreset,
  evaluateKeyframeSegment,
  sampleKeyframeCurve,
  type CurvePreset,
  type CurveSample,
} from "./curves.js";
export {
  affectedProfessionalCacheRanges,
  applyProfessionalTimelineCommand,
  emptyProfessionalTimelineState,
  evaluateTimeRemap,
  evaluateTimeRemapForPreview,
  evaluateTimeRemapForRender,
  professionalStateMetadataKey,
  readProfessionalTimelineState,
  validateBridgeBoundarySamples,
  writeProfessionalTimelineState,
  type AdjustmentLayerDefinition,
  type AdvancedBridgeDefinition,
  type BridgeBoundaryQaReport,
  type BridgeBoundarySample,
  type CompoundDefinition,
  type ProfessionalAudioBehavior,
  type ProfessionalEffect,
  type ProfessionalMutation,
  type ProfessionalTake,
  type ProfessionalTakeStack,
  type ProfessionalTimelineCommand,
  type ProfessionalTimelineState,
  type TimeRemapDefinition,
  type TimeRemapPoint,
} from "./professional.js";
export {
  buildProfessionalSourceEdit,
  resolveThreePointEdit,
  type BuiltProfessionalSourceEdit,
  type ProfessionalSourceMarks,
  type ProfessionalSourcePatch,
  type ResolvedThreePointEdit,
} from "./source-edit.js";
export {
  buildTimelineDerivedIndexes,
  TimelineDerivedIndexCache,
  ownerPropertyIndexKey,
  queryActiveVisualLayers,
  queryClipsAtFrame,
  queryClipsOverlappingRange,
  queryNearbyClips,
  queryVisibleClipsOverlappingRange,
  searchTimelineIndex,
  type ClipIntervalIndexEntry,
  type RenderDependencyIndexSource,
  type TimelineDerivedIndexSources,
  type TimelineDerivedIndexes,
  type TimelineEntityKind,
  type TranscriptPhraseIndexSource,
} from "./derived-indexes.js";
export {
  diffTimelineSnapshots,
  type TimelineChangeKind,
  type TimelineEntityChange,
  type TimelineSnapshotDiff,
} from "./diff.js";
export { createReferenceTimelineFixture, createStudioTimelineFixture } from "./fixture.js";
export { deserializeTimelineSnapshot, serializeTimelineSnapshot } from "./serialization.js";
export {
  executeTimelineDocumentEdit,
  timelineDocumentToSnapshot,
  timelineSnapshotToDocument,
  type TimelineDocumentEditResult,
} from "./document-adapter.js";

export interface TimelineOwnership {
  readonly authority: "integer-master-frame";
  readonly diagnostics: GeneratedDiagnosticCategory;
}

export const timelinePackageBoundary: TimelineOwnership = {
  authority: "integer-master-frame",
  diagnostics: "timeline",
};
