import { qaHash, type QaRuleDefinition } from "./contracts.js";

const rule = (
  id: string,
  category: QaRuleDefinition["category"],
  stage: QaRuleDefinition["stage"],
  title: string,
  blocking: boolean,
  description: string,
): QaRuleDefinition => ({
  schemaVersion: "1.0.0",
  id,
  version: "1.0.0",
  category,
  stage,
  title,
  defaultSeverity: blocking ? "error" : "warning",
  blocking,
  evaluatorVersion: "chai-qa-evaluator-v1",
  description,
});

export const centralizedQaRules = (): readonly QaRuleDefinition[] => [
  rule(
    "qa.pre.schema",
    "schema",
    "pre-render",
    "Project schema is valid",
    true,
    "All authoritative project documents validate.",
  ),
  rule(
    "qa.pre.media",
    "media",
    "pre-render",
    "Media dependencies resolve",
    true,
    "Required media and generated dependencies exist and match identity.",
  ),
  rule(
    "qa.pre.timeline",
    "timeline",
    "pre-render",
    "Frame ranges and durations are valid",
    true,
    "Timeline and requested output range are exact and bounded.",
  ),
  rule(
    "qa.pre.capability",
    "capability",
    "pre-render",
    "Capabilities have accepted render paths",
    true,
    "No unsupported capability enters execution.",
  ),
  rule(
    "qa.pre.font",
    "font",
    "pre-render",
    "Fonts resolve",
    true,
    "Every render font is pinned and available.",
  ),
  rule(
    "qa.pre.composition",
    "composition",
    "pre-render",
    "Compositions validate",
    true,
    "Native composition discovery and dependencies pass.",
  ),
  rule(
    "qa.pre.proxy",
    "proxy",
    "pre-render",
    "Final source policy passes",
    true,
    "Proxy media cannot silently enter a final output.",
  ),
  rule(
    "qa.pre.alpha",
    "alpha",
    "pre-render",
    "Alpha contract is coherent",
    true,
    "Profile, sources, and compositor agree on alpha.",
  ),
  rule(
    "qa.pre.audio",
    "audio",
    "pre-render",
    "Audio graph validates",
    true,
    "One authoritative audio graph and output layout are valid.",
  ),
  rule(
    "qa.pre.rights",
    "rights",
    "pre-render",
    "Delivery rights are resolved",
    true,
    "Every delivery asset has sufficient rights evidence.",
  ),
  rule(
    "qa.pre.trust",
    "trust",
    "pre-render",
    "Trust policy passes",
    true,
    "Untrusted executable content remains isolated.",
  ),
  rule(
    "qa.pre.disk",
    "disk",
    "pre-render",
    "Disk safety margin passes",
    true,
    "Output and temporary work fit with the frozen margin.",
  ),
  rule(
    "qa.pre.output-path",
    "output",
    "pre-render",
    "Output path is safe",
    true,
    "Output path is bounded, writable, and non-conflicting.",
  ),
  rule(
    "qa.pre.environment",
    "environment",
    "pre-render",
    "Environment compatibility passes",
    true,
    "Strict outputs use a compatible pinned environment.",
  ),
  rule(
    "qa.post.structure",
    "output",
    "post-render",
    "Output structure matches profile",
    true,
    "Readability, duration, dimensions, FPS, codecs, audio, frames, and hash match.",
  ),
  rule(
    "qa.post.audio",
    "audio",
    "post-render",
    "Audio measurements pass",
    true,
    "Silence, clipping, loudness, peak, channels, sync, and duration meet policy.",
  ),
  rule(
    "qa.post.visual",
    "visual",
    "post-render",
    "Boundary and continuity frames pass",
    true,
    "Endpoints, boundaries, alpha, proxy source, blank, freeze, and transitions pass.",
  ),
  rule(
    "qa.post.fidelity.strict",
    "visual",
    "post-render",
    "Strict fidelity frame matches",
    true,
    "Same-environment normalized pixels match exactly.",
  ),
  rule(
    "qa.post.fidelity.perceptual",
    "visual",
    "post-render",
    "Approved perceptual comparison passes",
    false,
    "Cross-environment metric uses fixture-measured thresholds.",
  ),
  rule(
    "qa.post.caption",
    "caption",
    "post-render",
    "Caption QA passes",
    true,
    "Readability, collision, safe zone, line length, speed, and phrase sync pass.",
  ),
  rule(
    "qa.post.sync",
    "sync",
    "post-render",
    "Timeline synchronization passes",
    true,
    "VO, captions, music, SFX, long timeline, and engine boundaries stay exact.",
  ),
  rule(
    "qa.review.checklist",
    "visual",
    "human-review",
    "Required visual review is recorded",
    true,
    "A human records every required review frame and category.",
  ),
];

export const qaRuleSetIdentity = (rules: readonly QaRuleDefinition[] = centralizedQaRules()): string =>
  qaHash(rules.map(({ id, version, evaluatorVersion }) => ({ id, version, evaluatorVersion })));
